# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0821404aac243dc0e378a09c89411ee480e2bd32ef2670d9039c0d5111162691825f7dbd2bea37f780b94115aa921b698e71d06a50019f4ff15a7ed699e1c854

test:
  secret_key_base: bb9b61ec98bfe723c0025d812184f1dfcdc0134ec25159147887b93fd3f9be73c8b0c0726aea138b56f2cda1d7142393abd5803a0562b188c31ab9351d3bf9f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
